
package ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "TimeService", targetNamespace = "http://endpoint.ws/", wsdlLocation = "http://localhost:41824/orderviewer/TimeService?wsdl")
public class TimeService_Service
    extends Service
{

    private final static URL TIMESERVICE_WSDL_LOCATION;
    private final static WebServiceException TIMESERVICE_EXCEPTION;
    private final static QName TIMESERVICE_QNAME = new QName("http://endpoint.ws/", "TimeService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:41824/orderviewer/TimeService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TIMESERVICE_WSDL_LOCATION = url;
        TIMESERVICE_EXCEPTION = e;
    }

    public TimeService_Service() {
        super(__getWsdlLocation(), TIMESERVICE_QNAME);
    }

    public TimeService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns TimeService
     */
    @WebEndpoint(name = "TimeServiceImplPort")
    public TimeService getTimeServiceImplPort() {
        return super.getPort(new QName("http://endpoint.ws/", "TimeServiceImplPort"), TimeService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TimeService
     */
    @WebEndpoint(name = "TimeServiceImplPort")
    public TimeService getTimeServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://endpoint.ws/", "TimeServiceImplPort"), TimeService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TIMESERVICE_EXCEPTION!= null) {
            throw TIMESERVICE_EXCEPTION;
        }
        return TIMESERVICE_WSDL_LOCATION;
    }

}
