
package ws.client;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebService(name = "TimeService", targetNamespace = "http://endpoint.ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TimeService {


    /**
     * 
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "currentTime", targetNamespace = "http://endpoint.ws/", className = "ws.client.CurrentTime")
    @ResponseWrapper(localName = "currentTimeResponse", targetNamespace = "http://endpoint.ws/", className = "ws.client.CurrentTimeResponse")
    public XMLGregorianCalendar currentTime();

}
